### ISSUE TITLE
User should be able to add comments to issues.

### ISSUE THREAD

**Issue by vaishnavi3001** [vaishnavi3001/jira-project#56]

**Comment by amhaske** [comment]
Create a comment component for the user to drop comments on an issue, following is the reference for frontend:
<img width="794" alt="comments" src="https://user-images.githubusercontent.com/26690642/159812712-57669d94-9e6e-4a06-bfd4-73f6f6abf93a.png">

**Comment by amhaske** [comment]
Added comments section to the issue details form:
<img width="979" alt="comments" src="https://user-images.githubusercontent.com/26690642/161363991-b86b85e4-bdf8-4a0d-9f3d-e5d8f1a70553.png">

**Comment by amhaske** [comment]
The submitted comments are also added in the backend.
