### ISSUE TITLE
A user should be able to invite a user to a project

### ISSUE THREAD

**Issue by vaishnavi3001** [vaishnavi3001/jira-project#85]

**Comment by amhaske** [comment]
Add an option on the project details page to invite a user to join the project.

**Comment by amhaske** [comment]
A sample UI reference is attached below:
![Screenshot 2022-04-14 at 2 51 04 PM](https://user-images.githubusercontent.com/26690642/163457326-3aa51571-6892-4fab-8256-5059b73add2f.png)
